# ----------------------------------------------
# |               BossTweaks v1.0              |
# |                 Config file                |
# ----------------------------------------------

# ---------------- ENDER DRAGON ----------------
# This section contains values that only affect the Ender Dragon boss fight

# Controls whether the dragon battle should be modified by the plugin. (true = enabled)
dragonEnabled: true

# Toggles whether TNT should be spawned when the Ender Dragon takes damage
tntEnabled: true

# Controls whether a dragon egg is dropped on dragon death
dragonEggDrop: false

# Controls whether an elytra is dropped on dragon death
elytraDrop: false

# ------------------- WITHER -------------------
# This section contains values that only affect the wither boss fight

# Controls whether the wither battle should be modified by the plugin. (true = enabled)
witherEnabled: true


# -------------------- MISC --------------------
# This section contains values that don't fit in the main categories

# Controls whether the plugin should check for updates
checkForUpdates: true

# Do not change this, this is automatically changed when needed
configRevision: 1

# ---------- ADDED AFTER INITIAL USE -----------
# Parameters that were added to the config file after it was initially generated