name: BossTweaks
main: com.sidpatchy.BossTweaks.BossTweaks
version: 1.0-SNAPSHOT
author: Sidpatchy
api-version: 1.16
permissions:
  BossTweaks.*:
    description: Gives the player all permissions
    default: op


